import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define the initial state for authentication
interface AuthState {
  user: {
    _id: string;
    name: string;
    email: string;
    phone: string;
    role: string;
    address: string;
  } | null;
}

const initialState: AuthState = {
  user: null, 
};

// Create a slice for the authentication state
const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    setUser: (
      state,
      action: PayloadAction<AuthState['user']>
    ) => {
      state.user = action.payload;
    },
    logout: (state) => {
      state.user = null;
    },
  },
});

// Export the actions generated by the slice
export const { setUser, logout } = authSlice.actions;

// Export the reducer to be used in the store configuration
export default authSlice.reducer;
